spring:
  output:
    ansi:
      enabled: always
server:
  port: 8082
logging:
  level:
    com.nammok.blog: DEBUG
    org.springframework.cloud.contract: DEBUG
persons-api:
  endpoint: http://localhost:8080/persons